version: "3.9"
services:
  api:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
    environment:
      ENABLE_RERANKING: "true"
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "2",
              "services.api.app:app", "--bind", "0.0.0.0:8080"]

  worker:
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 3G