name: Bug Report
description: Report a bug or issue with DocFoundry
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true
        - label: I can reproduce this issue consistently
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - API Server
        - Search Engine
        - Indexer
        - VS Code Extension
        - Chrome Extension
        - Database
        - Documentation
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Some functionality affected)
        - Low (Minor issue or cosmetic)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, Windows 11, macOS 13]
        - Python Version: [e.g. 3.11.5]
        - DocFoundry Version: [e.g. 0.2.0 or commit hash]
        - Database: [e.g. PostgreSQL 15.3]
        - Browser: [e.g. Chrome 118, Firefox 119] (if applicable)
        - VS Code Version: [e.g. 1.84.0] (if applicable)
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages and Logs
      description: Any error messages, stack traces, or relevant log output
      placeholder: |
        Paste error messages and logs here...
        
        Please include:
        - Full error messages
        - Stack traces
        - Relevant log entries
        - Console output
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration files or environment variables (remove sensitive data)
      placeholder: |
        # .env file (remove sensitive values)
        DOCFOUNDRY_API=http://localhost:8001
        
        # config files
        # database settings
        # etc.
      render: yaml

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images/videos here or paste URLs...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - When did this start happening?
        - Does it happen consistently or intermittently?
        - Any recent changes to your setup?
        - Workarounds you've tried?
        - Related issues or discussions?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this issue?
      options:
        - label: I would be willing to submit a pull request to fix this bug
          required: false