name: ci

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Format check (black)
      run: |
        black --check . --exclude=".venv|htmlcov|.pytest_cache|__pycache__|temp"
      continue-on-error: true
    
    - name: Lint (flake8)
      run: |
        flake8 . --exclude=".venv,htmlcov,.pytest_cache,__pycache__,temp" --max-line-length=100
      continue-on-error: true
    
    - name: Type check (mypy)
      run: |
        mypy . --exclude=".venv|htmlcov|.pytest_cache|__pycache__|tests|temp" --ignore-missing-imports
      continue-on-error: true
    
    - name: Security scan (bandit)
      run: |
        bandit -r . -x tests,temp,.venv --format json --severity-level medium
      continue-on-error: true
    
    - name: Vulnerability scan (pip-audit)
      run: |
        pip-audit --format=json
      continue-on-error: true
    
    - name: Tests
      run: |
        python -m pytest tests/ -v --tb=short
      continue-on-error: true