name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Lint & unit tests
        run: |
          python -m pytest -q || true  # keep pipeline permissive until tests exist
      - name: Build Docker images
        run: |
          docker build -t docfoundry-api -f services/api/Dockerfile .
          docker build -t docfoundry-worker -f services/worker/Dockerfile .
          docker build -t docfoundry-mcp -f services/mcp/Dockerfile .
      - name: Save Docker images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: |
            **/Dockerfile
  # Optional: push to registry & run migrations in staging